### ISSUE TITLE
Unable to load library 'CueSDK': The specified module could not be found

### ISSUE THREAD

**Issue by SwezedCode** [FiercestT/corsair-icue-java#1]
Whenever I run the script it tells me that I am missing a library. I don't seem to find any DLL provided in the project so I am a little confused by how this works.

**Comment by FiercestT** [comment]
My apologies, I noticed the issue the other day when trying to implement it to a project. From what I believe, it is an issue with JNA being unable to find the CueSDK.dll in the jar.
I am working on a project update and port to Gradle in my spare time. I will commit the fixes in the near future.

**Comment by FiercestT** [comment]
Repo has been migrated to https://github.com/FiercestT/corsair-cue-java. Issue has been resolved on my end. Please make an issue on the new repo if anything persists. Thanks!
